"""Deep learning support tool - provides PyTorch/TensorFlow scaffolding and guidance."""

import os
from langchain_core.tools import tool


@tool
def generate_dl_scaffold(
    workspace_dir: str,
    task_type: str,
    input_shape: str,
    num_classes: int = 2,
    framework: str = "pytorch",
) -> str:
    """Generate a deep learning training scaffold (boilerplate code) for the specified task.
    Creates a ready-to-customize training script with proper data loading, model definition,
    training loop, and evaluation.

    Args:
        workspace_dir: Path to the project workspace directory.
        task_type: Type of task - "tabular_classification", "tabular_regression", "image_classification", "text_classification", "time_series".
        input_shape: Shape description (e.g., "150" for 150 features, "3x224x224" for images, "100" for sequence length).
        num_classes: Number of output classes (for classification tasks).
        framework: "pytorch" or "tensorflow".
    """
    abs_workspace = os.path.expanduser(workspace_dir)
    src_dir = os.path.join(abs_workspace, "src")
    os.makedirs(src_dir, exist_ok=True)

    if framework == "pytorch":
        code = _generate_pytorch_scaffold(task_type, input_shape, num_classes)
    elif framework == "tensorflow":
        code = _generate_tensorflow_scaffold(task_type, input_shape, num_classes)
    else:
        return f"[ERROR] Unknown framework: {framework}. Use 'pytorch' or 'tensorflow'."

    script_path = os.path.join(src_dir, f"train_dl_{framework}.py")
    with open(script_path, "w") as f:
        f.write(code)

    return (
        f"Deep learning scaffold generated at: {script_path}\n"
        f"Framework: {framework}\n"
        f"Task: {task_type}\n"
        f"Input shape: {input_shape}\n"
        f"Output classes: {num_classes}\n\n"
        f"This is a starting scaffold. Customize the model architecture, "
        f"hyperparameters, and data loading as needed for your specific dataset."
    )


def _generate_pytorch_scaffold(task_type, input_shape, num_classes):
    """Generate PyTorch training scaffold."""

    if task_type in ("tabular_classification", "tabular_regression"):
        input_dim = int(input_shape.split("x")[0]) if "x" in input_shape else int(input_shape)
        is_regression = "regression" in task_type
        output_dim = 1 if is_regression else num_classes
        loss_fn = "nn.MSELoss()" if is_regression else "nn.CrossEntropyLoss()"

        return f'''"""PyTorch training script for {task_type} - Generated by ModelForge."""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, mean_squared_error, r2_score
import json
import os

# ── Configuration ───────────────────────────────────────────────────────

BATCH_SIZE = 32
EPOCHS = 100
LEARNING_RATE = 1e-3
HIDDEN_DIMS = [128, 64, 32]
DROPOUT = 0.3
PATIENCE = 10  # Early stopping patience
INPUT_DIM = {input_dim}
OUTPUT_DIM = {output_dim}
IS_REGRESSION = {is_regression}

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {{device}}")


# ── Model Definition ────────────────────────────────────────────────────

class TabularNet(nn.Module):
    def __init__(self, input_dim, hidden_dims, output_dim, dropout=0.3):
        super().__init__()
        layers = []
        prev_dim = input_dim
        for h_dim in hidden_dims:
            layers.extend([
                nn.Linear(prev_dim, h_dim),
                nn.BatchNorm1d(h_dim),
                nn.ReLU(),
                nn.Dropout(dropout),
            ])
            prev_dim = h_dim
        layers.append(nn.Linear(prev_dim, output_dim))
        self.network = nn.Sequential(*layers)

    def forward(self, x):
        return self.network(x)


# ── Data Loading ────────────────────────────────────────────────────────

def load_data(data_path, target_column):
    """Load and preprocess data. Customize this for your dataset."""
    df = pd.read_csv(data_path)

    # Separate features and target
    X = df.drop(columns=[target_column])
    y = df[target_column]

    # Encode categorical features
    for col in X.select_dtypes(include=["object", "category"]).columns:
        X[col] = LabelEncoder().fit_transform(X[col].astype(str))

    # Encode target for classification
    label_encoder = None
    if not IS_REGRESSION:
        label_encoder = LabelEncoder()
        y = label_encoder.fit_transform(y)

    # Train/val/test split
    X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
    X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

    # Scale features
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_val = scaler.transform(X_val)
    X_test = scaler.transform(X_test)

    # Convert to tensors
    dtype_y = torch.float32 if IS_REGRESSION else torch.long
    train_ds = TensorDataset(torch.FloatTensor(X_train), torch.tensor(y_train.values if hasattr(y_train, "values") else y_train, dtype=dtype_y))
    val_ds = TensorDataset(torch.FloatTensor(X_val), torch.tensor(y_val.values if hasattr(y_val, "values") else y_val, dtype=dtype_y))
    test_ds = TensorDataset(torch.FloatTensor(X_test), torch.tensor(y_test.values if hasattr(y_test, "values") else y_test, dtype=dtype_y))

    return train_ds, val_ds, test_ds, scaler, label_encoder


# ── Training Loop ───────────────────────────────────────────────────────

def train(model, train_loader, val_loader, epochs, lr, patience):
    criterion = {loss_fn}
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=patience//2)

    best_val_loss = float("inf")
    patience_counter = 0
    history = {{"train_loss": [], "val_loss": []}}

    for epoch in range(epochs):
        # Train
        model.train()
        train_loss = 0
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            optimizer.zero_grad()
            output = model(X_batch)
            if IS_REGRESSION:
                output = output.squeeze()
            loss = criterion(output, y_batch)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()

        train_loss /= len(train_loader)

        # Validate
        model.eval()
        val_loss = 0
        with torch.no_grad():
            for X_batch, y_batch in val_loader:
                X_batch, y_batch = X_batch.to(device), y_batch.to(device)
                output = model(X_batch)
                if IS_REGRESSION:
                    output = output.squeeze()
                val_loss += criterion(output, y_batch).item()
        val_loss /= len(val_loader)

        scheduler.step(val_loss)
        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)

        if (epoch + 1) % 10 == 0:
            print(f"Epoch {{epoch+1}}/{{epochs}} - Train Loss: {{train_loss:.4f}} - Val Loss: {{val_loss:.4f}}")

        # Early stopping
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            patience_counter = 0
            torch.save(model.state_dict(), "../models/best_model.pth")
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"Early stopping at epoch {{epoch+1}}")
                break

    return history


# ── Evaluation ──────────────────────────────────────────────────────────

def evaluate(model, test_loader):
    model.eval()
    all_preds = []
    all_targets = []

    with torch.no_grad():
        for X_batch, y_batch in test_loader:
            X_batch = X_batch.to(device)
            output = model(X_batch)
            if IS_REGRESSION:
                all_preds.extend(output.squeeze().cpu().numpy())
            else:
                all_preds.extend(output.argmax(dim=1).cpu().numpy())
            all_targets.extend(y_batch.numpy())

    if IS_REGRESSION:
        mse = mean_squared_error(all_targets, all_preds)
        r2 = r2_score(all_targets, all_preds)
        print(f"Test MSE: {{mse:.4f}}, R2: {{r2:.4f}}")
        return {{"mse": mse, "r2": r2}}
    else:
        acc = accuracy_score(all_targets, all_preds)
        f1 = f1_score(all_targets, all_preds, average="weighted")
        print(f"Test Accuracy: {{acc:.4f}}, F1: {{f1:.4f}}")
        return {{"accuracy": acc, "f1": f1}}


# ── Main ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    # TODO: Update these paths for your dataset
    DATA_PATH = "../data/your_dataset.csv"
    TARGET_COLUMN = "target"

    os.makedirs("../models", exist_ok=True)
    os.makedirs("../results", exist_ok=True)

    print("Loading data...")
    train_ds, val_ds, test_ds, scaler, label_encoder = load_data(DATA_PATH, TARGET_COLUMN)

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE)
    test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE)

    print(f"Train: {{len(train_ds)}}, Val: {{len(val_ds)}}, Test: {{len(test_ds)}}")

    # Create model
    model = TabularNet(INPUT_DIM, HIDDEN_DIMS, OUTPUT_DIM, DROPOUT).to(device)
    print(f"Model parameters: {{sum(p.numel() for p in model.parameters()):,}}")

    # Train
    print("\\nTraining...")
    history = train(model, train_loader, val_loader, EPOCHS, LEARNING_RATE, PATIENCE)

    # Load best model and evaluate
    model.load_state_dict(torch.load("../models/best_model.pth", map_location=device))
    print("\\nEvaluating on test set...")
    metrics = evaluate(model, test_loader)

    # Save results
    with open("../results/dl_metrics.json", "w") as f:
        json.dump(metrics, f, indent=2)

    print(f"\\nResults saved to ../results/dl_metrics.json")
    print("Model saved to ../models/best_model.pth")
'''

    elif task_type == "image_classification":
        return f'''"""PyTorch image classification scaffold - Generated by ModelForge."""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms, models
import json
import os

# ── Configuration ───────────────────────────────────────────────────────

BATCH_SIZE = 32
EPOCHS = 30
LEARNING_RATE = 1e-4
NUM_CLASSES = {num_classes}
IMAGE_SIZE = 224

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ── Data Transforms ─────────────────────────────────────────────────────

train_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

val_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

# ── Model ───────────────────────────────────────────────────────────────

def create_model(num_classes, pretrained=True):
    """Use pretrained ResNet18 with custom classifier head."""
    model = models.resnet18(pretrained=pretrained)
    model.fc = nn.Sequential(
        nn.Dropout(0.3),
        nn.Linear(model.fc.in_features, num_classes),
    )
    return model

# TODO: Add data loading, training loop, and evaluation
# (similar structure to tabular scaffold above)

print("Image classification scaffold created.")
print("Update DATA_DIR, transforms, and model architecture as needed.")
'''

    else:
        return f'''"""PyTorch scaffold for {task_type} - Generated by ModelForge."""

# TODO: Implement custom scaffold for {task_type}
# Input shape: {input_shape}
# Num classes: {num_classes}

import torch
import torch.nn as nn

print("Scaffold for {task_type} created. Customize as needed.")
'''


def _generate_tensorflow_scaffold(task_type, input_shape, num_classes):
    """Generate TensorFlow/Keras training scaffold."""
    input_dim = int(input_shape.split("x")[0]) if "x" in input_shape else int(input_shape)
    is_regression = "regression" in task_type

    return f'''"""TensorFlow/Keras training script for {task_type} - Generated by ModelForge."""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import json
import os

# ── Configuration ───────────────────────────────────────────────────────

BATCH_SIZE = 32
EPOCHS = 100
LEARNING_RATE = 1e-3
INPUT_DIM = {input_dim}
NUM_CLASSES = {num_classes}
IS_REGRESSION = {is_regression}

# ── Model Definition ────────────────────────────────────────────────────

def create_model(input_dim, num_classes, is_regression):
    model = keras.Sequential([
        layers.Input(shape=(input_dim,)),
        layers.Dense(128, activation="relu"),
        layers.BatchNormalization(),
        layers.Dropout(0.3),
        layers.Dense(64, activation="relu"),
        layers.BatchNormalization(),
        layers.Dropout(0.3),
        layers.Dense(32, activation="relu"),
        layers.Dropout(0.2),
    ])

    if is_regression:
        model.add(layers.Dense(1))
        model.compile(optimizer=keras.optimizers.Adam(LEARNING_RATE),
                     loss="mse", metrics=["mae"])
    else:
        model.add(layers.Dense(num_classes, activation="softmax"))
        model.compile(optimizer=keras.optimizers.Adam(LEARNING_RATE),
                     loss="sparse_categorical_crossentropy", metrics=["accuracy"])

    return model

# ── Main ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    DATA_PATH = "../data/your_dataset.csv"
    TARGET_COLUMN = "target"

    os.makedirs("../models", exist_ok=True)
    os.makedirs("../results", exist_ok=True)

    # Load data
    df = pd.read_csv(DATA_PATH)
    X = df.drop(columns=[TARGET_COLUMN])
    y = df[TARGET_COLUMN]

    # Encode categoricals
    for col in X.select_dtypes(include=["object"]).columns:
        X[col] = LabelEncoder().fit_transform(X[col].astype(str))

    if not IS_REGRESSION:
        y = LabelEncoder().fit_transform(y)

    # Split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Scale
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # Create and train model
    model = create_model(INPUT_DIM, NUM_CLASSES, IS_REGRESSION)
    model.summary()

    callbacks = [
        keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True),
        keras.callbacks.ReduceLROnPlateau(patience=5),
    ]

    history = model.fit(X_train, y_train, validation_split=0.15,
                       epochs=EPOCHS, batch_size=BATCH_SIZE, callbacks=callbacks)

    # Evaluate
    results = model.evaluate(X_test, y_test)
    print(f"Test results: {{dict(zip(model.metrics_names, results))}}")

    # Save
    model.save("../models/best_model.keras")
    print("Model saved to ../models/best_model.keras")
'''
