"""Model card generator - creates standardized model documentation."""

import os
import json
import time
from langchain_core.tools import tool


@tool
def generate_model_card(
    workspace_dir: str,
    model_name: str,
    model_type: str,
    task_type: str,
    dataset_description: str,
    metrics: str,
    features_used: str,
    training_details: str = "",
    limitations: str = "",
    ethical_considerations: str = "",
) -> str:
    """Generate a standardized model card (Markdown) documenting the trained model.
    Model cards provide transparency about how a model was built, what it does well,
    and where it may fall short.

    Args:
        workspace_dir: Path to the project workspace directory.
        model_name: Name of the model (e.g., "RandomForest Churn Classifier").
        model_type: Algorithm type (e.g., "Random Forest", "XGBoost", "Neural Network").
        task_type: ML task type (e.g., "Binary Classification", "Multi-class Classification", "Regression").
        dataset_description: Description of the training data (rows, columns, source, date range).
        metrics: JSON string of evaluation metrics (e.g., '{"accuracy": 0.95, "f1": 0.94}').
        features_used: Comma-separated list of features used by the model.
        training_details: Additional training info (hyperparameters, cross-validation, etc.).
        limitations: Known limitations or failure modes.
        ethical_considerations: Fairness, bias, or privacy considerations.
    """
    abs_workspace = os.path.expanduser(workspace_dir)

    try:
        metrics_dict = json.loads(metrics)
    except (json.JSONDecodeError, TypeError):
        return f"[ERROR] Invalid metrics JSON: {metrics}"

    features_list = [f.strip() for f in features_used.split(",") if f.strip()]

    # Build metrics table
    metrics_rows = "\n".join(f"| {k} | {v} |" for k, v in metrics_dict.items())

    # Build features list
    features_md = "\n".join(f"- `{f}`" for f in features_list)

    card = f"""# Model Card: {model_name}

*Generated by ModelForge on {time.strftime("%Y-%m-%d %H:%M:%S")}*

## Model Details

| Property | Value |
|----------|-------|
| Model Name | {model_name} |
| Model Type | {model_type} |
| Task | {task_type} |
| Framework | scikit-learn / Python |
| Generated By | ModelForge |

## Intended Use

This model was built for **{task_type.lower()}** tasks. It is intended for use
in the context described by the training data below.

**Primary use case:** Automated predictions based on structured/tabular input data.

**Out-of-scope:** This model should not be used for high-stakes decisions without
human review. It has not been validated for production deployment.

## Training Data

{dataset_description}

## Features

The model uses the following input features:

{features_md}

## Performance Metrics

| Metric | Value |
|--------|-------|
{metrics_rows}

"""

    if training_details:
        card += f"""## Training Details

{training_details}

"""

    if limitations:
        card += f"""## Limitations

{limitations}

"""
    else:
        card += """## Limitations

- Model performance may degrade on data that differs significantly from training data.
- No drift detection or monitoring is built in.
- Feature distributions are assumed to remain stable over time.

"""

    if ethical_considerations:
        card += f"""## Ethical Considerations

{ethical_considerations}

"""
    else:
        card += """## Ethical Considerations

- Review model predictions for potential bias before deployment.
- Ensure training data is representative of the target population.
- Consider fairness implications if predictions affect individuals.

"""

    card += f"""## How to Use

```python
import joblib
import numpy as np

# Load model
model = joblib.load("models/best_model.pkl")

# Prepare input (example)
X = np.array([[...]])  # Shape: (n_samples, {len(features_list)})

# Predict
predictions = model.predict(X)
```

## Citation

If you use this model, please reference:
- **Built with:** [ModelForge](https://github.com/matej-01RAI/ModelForge)
- **Generated:** {time.strftime("%Y-%m-%d")}
"""

    # Write model card
    card_path = os.path.join(abs_workspace, "MODEL_CARD.md")
    with open(card_path, "w") as f:
        f.write(card)

    return f"Model card generated at: {card_path}"
